#!/bin/bash
#use this file to cheange default parameters for plots
# //////////////////////////////////////////////////////////////////////////////

#Path to input file directory
pth2inptf=../bin/


#outfiles
outfile=output.ps

# #colormaps
# landcpt=land_man.cpt
# bathcpt=bath_man.cpt


# //////////////////////////////////////////////////////////////////////////////
# Set default REGION 
west=2 #17 #19.5
east=12 #30 #29
south=41.5 #34
north=49.5 #42
projscale=5500000
frame=1

# length of plot scale (Km)
sclength=100

logo_pos="BL/.1c/.1c"

# scale parameters for velocities
# vsclon=22.34 #delete
# vsclat=37.68 #delete
vscmagn=2
VSC=0.5

strscmagn=5
STRSC=.160
ROTSC=.6
ROT_wedge_mag=.1  #(marcsec/yr)
# strsclon=20.4 #delete
# strsclat=36.3 #delete

legendc="-Jx1i -R0/8/0/8 -Dx20.5c/12.6c+w5c/4.6c+jBL"	
